# Generated by Django 5.2.8 on 2025-11-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_shipment_latitude_shipment_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.user'),
        ),
    ]
