# Generated by Django 5.2.8 on 2025-11-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_shipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envios.truck'),
        ),
    ]
