# Generated by Django 5.2.8 on 2025-11-10 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_guide_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to='envios.user'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_shipments', to='envios.user'),
        ),
    ]
