# Generated by Django 5.2.8 on 2025-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0008_shipment_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='distance_traveled_km',
            field=models.FloatField(default=0, help_text='Distancia total recorrida por el repartidor en km'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_tracking_latitude',
            field=models.FloatField(blank=True, help_text='Última lat para cálculo de distancia', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_tracking_longitude',
            field=models.FloatField(blank=True, help_text='Última lon para cálculo de distancia', null=True),
        ),
    ]
