# Generated by Django 5.2.8 on 2025-11-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0009_shipment_distance_traveled_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
