# Generated by Django 5.2.8 on 2025-11-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0010_remove_shipment_warehouse_delete_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='simulation_step',
            field=models.IntegerField(default=0, help_text='Paso actual en la simulación de ruta (0-10)'),
        ),
    ]
